apiVersion: v1
kind: Pod
metadata:
  name: secret-pod
spec:
  containers:
    - name: web
      image: nginx

      env:
        - name: app_env_username
          valueFrom:
            secretKeyRef:
              name: sample-secret
              key: app_username
        - name: app_env_passowrd
          valueFrom:
            secretKeyRef:
              name: sample-secret
              key: app_password