apiVersion: v1
kind: Pod
metadata:
  name: configmap-pod
spec:
  containers:
    - name: web
      image: nginx

      env:
        - name: app_env_username
          valueFrom:
            configMapKeyRef:
              name: sample-config
              key: app_username
        - name: app_env_passowrd
          valueFrom:
            configMapKeyRef:
              name: sample-config
              key: app_password