apiVersion: v1
kind: Pod
metadata:
  namespace: default
  name: custom-dns
spec:
  containers:
    - name: busybox
      image: busybox
      command:
      - sleep
      - "3600"
  dnsPolicy: "None"
  dnsConfig:
    nameservers:
      - 8.8.8.8
    searches:
      - ns1.svc.cluster-domain.example
      - my.dns.search.suffix
    options:
      - name: ndots
        value: "2"
      - name: edns0