apiVersion: v1
kind: Deployment
metadata:
  name: wordpress

spec:

  strategy:
    type: Recreate

  template:
    metadata:
      labels:
        app: wordpress
    spec:
      containers:
        - name: wordpress
          image: ???
          ports:
            - containerPort: ???
          env:
            - name: WORDPRESS_DB_HOST
              value: ??? # Your database service

            - name: WORDPRESS_DB_PASSWORD
              ??? # Read the password from database's secret

          volumeMounts:
            - name: ???
              mountPath: /var/www/html

      volumes:
        - name: wordpress-persistent-storage
          persistentVolumeClaim:
            claimName: ???